language: ruby
cache: bundler
sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0

before_install: gem install bundler
script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - travis@sterex.de
    on_failure: change
    on_success: change

